export * from "./spinnerIcon"
export const logo = require("./logo-lg.png")
export const logo2 = require("./logo-lg-2.png")
export const googlePlayIcon = require("./google-play.png")
export const appStoreIcon = require("./app-store.png")
export const companyIcon = require("./company_logo.jpeg")
export const paymentMethodsImage = require("./payment-methods.png")
export const boCongThuong = require("./bo-cong-thuong.png")
export const shippingMethodsImage = require("./shippings.png")
export const zaloIcon = require("./zalo-icon.png")
